---
version: '3.4'
services:
  fastapi-tests:
    env_file: .env.test
    build:
      context: .
      dockerfile: test.Dockerfile
    container_name: fastapi-application-test
    depends_on:
      - weaviate
      - t2v-transformers
    volumes:
      - type: bind
        source: ./tests/logs
        target: /app/tests/logs
  weaviate:
    env_file: .env.test
    image: semitechnologies/weaviate:1.21.1
    container_name: weaviate-test
    ports:
      - '8080:8080'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: "on-failure"
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    container_name: t2v-transformers-test
    environment:
      ENABLE_CUDA: '0'
volumes:
  weaviate_data:
...