import os


def get_int(name, default):
    return int(os.getenv(name, str(default)))


MAX_UPLOAD_BYTES = get_int("MAX_UPLOAD_BYTES", 25 * 1024 * 1024)
UPLOAD_READ_CHUNK_BYTES = get_int("UPLOAD_READ_CHUNK_BYTES", 1024 * 1024)
MAX_CHUNKS_PER_UPLOAD = get_int("MAX_CHUNKS_PER_UPLOAD", 5000)
VECTORSTORE_ADD_BATCH_SIZE = get_int("VECTORSTORE_ADD_BATCH_SIZE", 128)
CHUNK_OVERLAP = get_int("CHUNK_OVERLAP", 20)
CITATION_PREVIEW_CHARS = get_int("CITATION_PREVIEW_CHARS", 240)
LIST_DOCUMENT_CHUNK_SCAN_LIMIT = get_int("LIST_DOCUMENT_CHUNK_SCAN_LIMIT", 10000)
