name: tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: python -m pip install poetry==2.3.2

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run pytest .
